server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Populus-euphratica/SpringCloud2020Config.git
          search-paths: SpringCloud2020Config
          default-label: master
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

